### ISSUE TITLE
could not get the .npz result and summary result

### ISSUE THREAD

**Issue by zofieLin** [fuxialexander/marvel#1]
Hi,
I am trying to test marvel with the test_input file but could not get the ".ngz " result and summary result, and didn't have anything error messages, but with a lot of log messages related with R install.packages('glmpath'), however, I make sure that my R has installed "glmpath" already. 
This is my codes for testing:
> conda activate fuxialexander-marvel-1.1dev
/software/Nextflow/20.07.1/bin/nextflow run /home/software/marvel -profile conda --fasta /psychipc01/disk2/references/GATK/bundle/2.8/hg19/ucsc.hg19.fasta --enhancer /home/software/marvel/test_input/regions/enhancer.bed --promoter /home/software/marvel/test_input/regions/promoter.bed --vcf /home/software/marvel/test_input/variants/test.vcf.gz --vcf_index  /home/software/marvel/test_input/variants/test.vcf.gz.tbi --phenocov /home/software/marvel/test_input/samples/pheno_covar.txt --chunk_size 100 --permutation_multiplier 10 --motif_scan_threshold 0.0001 --outdir /home/software/marvel/test2 -w /home/software/marvel/test2/work --max_memory '20.GB' --max_cpus 1

I also tried "nextflow main.nf -profile test,conda", and it generated the same result and log message. Attached with the result info and log file.
Thank you!

[test.result.tree.txt](https://github.com/fuxialexander/marvel/files/5742871/test.result.tree.txt)
[test.sh.log](https://github.com/fuxialexander/marvel/files/5742872/test.sh.log)

**Comment by fuxialexander** [comment]
That sounds like a path problem. Can you try to run the nextflow command in the cloned directory?

**Comment by zofieLin** [comment]
Thanks, the nextflow runs well in the marvel directory, do you mean running like this:
![image](https://user-images.githubusercontent.com/51777970/103601288-480b4280-4f44-11eb-875e-e490ca944885.png)

**Comment by fuxialexander** [comment]
I meant running the full code you mentioned above. The error log says it cannot find the glmpath tar.gz file, which should be in the cloned directory. I didn't include the corresponding path to that file in `main.nf` so that might be the issue.

**Comment by fuxialexander** [comment]
Actually you can manually install the package (if you haven't done so) by `R CMD INSTALL glmpath_0.98.tar.gz` and comment out https://github.com/fuxialexander/marvel/blob/cd8575a64be48555be6497da70894efc5ce7e24f/main.nf#L171-L172 

Note that there is a bug in the glmpath on CRAN, which is why I use this patched package.
Install first using CRAN is to ensure all dependencies are installed, and then the patched package is installed to overwrite the bug.

**Comment by zofieLin** [comment]
Thank you so much, I reinstalled the glmpth again and it runs well.
And I have another question about the final result under "summary", it generated the same result in both enhancer and promoter, however, this region is only contained in the input "enhancer.bed" but not in "promoter.bed", so why it also generated that motif region in the summary/promoter_results*?  also, the "enhancer_results.collected.npz_qqplot.pdf" and "promoter_results.collected.npz_qqplot.pdf" is exactly the same. 
![image](https://user-images.githubusercontent.com/51777970/103843026-03151680-50d2-11eb-9a64-ddbf93ecbf0b.png)
![image](https://user-images.githubusercontent.com/51777970/103843283-80d92200-50d2-11eb-98e5-65a455f57f2c.png)

Thanks!

**Comment by fuxialexander** [comment]
Thanks for your report! I tried to push a fix https://github.com/fuxialexander/marvel/commit/837d060e9f9fe3c1a089c01839035faeb1664c1a. Please see whether it works for you now.
The old code seems to combine the results of both enhancer and promoter

**Comment by zofieLin** [comment]
it comes with the other issues like this:
```
Error executing process > 'collect_gene_chunk (null)'

Caused by:
  Process `collect_gene_chunk (null)` terminated with an error exit status (1)

Command executed:

  collect_results.py -n gene -r ./ -o ./

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/software/marvel/bin/collect_results.py", line 29, in <module>
      profiles = vstack(profiles)
    File "/home/software/miniconda3/lib/python3.7/site-packages/scipy/sparse/construct.py", line 501, in vstack
      return bmat([[b] for b in blocks], format=format, dtype=dtype)
    File "/home/software/miniconda3/lib/python3.7/site-packages/scipy/sparse/construct.py", line 550, in bmat
      raise ValueError('blocks must be 2-D')
  ValueError: blocks must be 2-D
```

**Comment by fuxialexander** [comment]
Have you installed the patched version of glmpath as I mentioned above? This is exactly the issue of the CRAN version.

**Comment by zofieLin** [comment]
Yes, exactly. It runs well before editing 'bin/collect_results.py ' but generated duplicate results in enhancer and promoter. Then when I editing the 'bin/collect_results.py ' as you mentioned in [837d060](https://github.com/fuxialexander/marvel/commit/837d060e9f9fe3c1a089c01839035faeb1664c1a) and it comes with that error messages. I also try to rerun the script before editing, it still runs well with the complete result (still duplicate).

**Comment by fuxialexander** [comment]
I see. Let me look into it. Thanks for your feedback!

**Comment by fuxialexander** [comment]
Ah, actually it's not related to glmpath. It's a naive overlook of file path... Should be fixed in https://github.com/fuxialexander/marvel/commit/a5d56713a23710861e4eabe22a62a7a7fac7965d

**Comment by zofieLin** [comment]
Thank you so much, it runs well now.
By the way, it seems no output for the gene_results (have points in the qqplot but absent in csv table), is there any way to generate all the results instead of the one after filter?
And, if I only have a vcf containing variants of cases but without variants of control (e.g. denovo variants), is there any "simple" way for me to just do the motif annotation? 
Thanks!

**Comment by fuxialexander** [comment]
I think you can set the `fdr_cutoff` parameter to 1 to avoid filtering.
For annotate VCF for motif change, I guess VEP and Motifbreakr (R package) would be a better choice.

**Comment by fuxialexander** [comment]
Closed as the problem has been solved
