### ISSUE TITLE
--max_cpus didn't work

### ISSUE THREAD

**Issue by zofieLin** [fuxialexander/marvel#2]
Hi, I tried to run marvel for motif prediction but the jobs always killed by the exceeded limit of cpus, seems the parameter `--max_cpus` didn't work.
I try to set `--max_cpus 1` or ` --max_cpus 2` etc., they all have similar results, like
![image](https://user-images.githubusercontent.com/51777970/110579494-e95f8080-81a1-11eb-9e2a-d4dc5ea76c92.png)
![image](https://user-images.githubusercontent.com/51777970/110579528-fb412380-81a1-11eb-8848-bfc77cf31d6f.png)
number "4" in the log file is the cpu I set when the job summitted, not the same with what I set in marvel's script `--max_cpus` 
Could you please help me have a check?
Thank you.

**Comment by fuxialexander** [comment]
Can you try to add 
```
cpus 4
executor 'pbs'
```
to the beginning of each `process x {...}` block?

e.g. 
```
process predict {
cpus 4
executor 'pbs'
}
```
Not sure whether it will work as I don't have previous experience with PBS.

**Comment by fuxialexander** [comment]
Ah, maybe you can also set `--cpus 2` when running. It seems that `max_cpus` is not the direct variable that controlling the cpu usage.
https://www.nextflow.io/docs/latest/executor.html#pbs-torque
https://www.nextflow.io/docs/latest/process.html#process-cpus

**Comment by zofieLin** [comment]
Hi alex, 
Seems it doesn't work will `--cpus *`or `process x {cpus *}`
not effect with `--cpus *`.
Because it always occured in the `scan_test` step, so I try to add `process x {cpus *}` in this step,
![image](https://user-images.githubusercontent.com/51777970/111023679-54fd5400-8415-11eb-8118-2b85c54916dd.png)
at first, I didn't add `queue '*'`, but it would come up with errror `No default queue specified,` then I added queue, it still didn't work. 
Alao, I noticed that in the log file, the executor is "local", so I also try `process x {cpus 4 executor 'local'}`, but still didn't work. Is there anyother methods to control the cpus in the step of  `scan_test`. By the way, I only input with 18 variants, very little variants.
![image](https://user-images.githubusercontent.com/51777970/111024918-246ce880-841c-11eb-8fbd-ad10f5ea7fd0.png)

Thanks.

**Comment by zofieLin** [comment]
another problem still about step `scan_test`, with error about phenotype covariate (full log file in the attachment).
[test.log.txt](https://github.com/fuxialexander/marvel/files/6134458/test.log.txt)
`AttributeError: 'DataFrame' object has no attribute 'pheno'`

**Comment by fuxialexander** [comment]
Ah you may want to remove the "label 'process_heavy'" line as it will direct nextflow to use more cpu for the process

**Comment by zofieLin** [comment]
still didn't work.
![image](https://user-images.githubusercontent.com/51777970/111274009-70fc3200-866f-11eb-9a5b-c457453a486b.png)

**Comment by fuxialexander** [comment]
I'm not sure then. Maybe you can take the code of `scan_test` process https://github.com/fuxialexander/marvel/blob/7fed7515ebe0a3fde9e842c0ee81a39f4413b457/main.nf#L398 and run the script yourself without using nextflow? That might give you better control of cores to use.
Also you might want to check the number of cores used by `numpy` matrix operation, by default it will use all cores. https://stackoverflow.com/questions/17053671/python-how-do-you-stop-numpy-from-multithreading

**Comment by zofieLin** [comment]
Thanks, I try to minimize the region of promoter and enhancer file to those have overlap with my input variants, and it makes sense to reduce the CPU when running, but I am not sure whether it will affect the final result.

I also have another question that, the  *.pwm in /motifs are the same as the one I download from HOCOMOCO, it there pwm result of the alternative allele? Or, does marvel could produce the motif score about reference allele and alternative allele?

**Comment by fuxialexander** [comment]
Somehow I forgot to reply to you...sorry. The ones in *.pwm in /motifs is directly downloaded from HOCOMOCO with no modification. MARVEL will scan patient sequence using the motif and store the motif scanning score, but will not specifically compare it to the reference one. Instead the score will be compared between cases and controls.
