### ISSUE TITLE
Error executing process > 'collect_region_chunk"

### ISSUE THREAD

**Issue by FTD2018** [fuxialexander/marvel#3]
Hi, thanks for developing the MARVEL .
I have tried to run it, but encounter an error:
![图片](https://user-images.githubusercontent.com/34161876/120886687-b4888b80-c621-11eb-8f04-b471a1c3e7dd.png)
I have no ideas what's wrong
And the input is 
![图片](https://user-images.githubusercontent.com/34161876/120886749-1cd76d00-c622-11eb-8c3d-de8d1d7fb7f2.png)

Could you help me have a check?
Thank you

**Comment by fuxialexander** [comment]
Can you add a breakpoint on line 32 of `bin/collect_results.py` or simply print out `profiles[0]` before line 32?

**Comment by FTD2018** [comment]
> 
> 
> Can you add a breakpoint on line 32 of `bin/collect_results.py` or simply print out `profiles[0]` before line 32?

I have added print(profiles[0]) before line32, and the results is:
![图片](https://user-images.githubusercontent.com/34161876/121451918-0c801300-c9d1-11eb-9d6b-8e360e5a0ff3.png)

And it seems like the list of profiles is empty?
So is it the problem with my input?

thank you

**Comment by FTD2018** [comment]
The input is:
![图片](https://user-images.githubusercontent.com/34161876/121452486-122a2880-c9d2-11eb-86a8-7e67f7a9958b.png)
I have modified the "test.config" in the conf folder, but I didn't change the "weights" parameter.
The command is "nextflow main.nf -profile test -resume"

**Comment by fuxialexander** [comment]
In that case, can you try to add a print(i) after line 29 and check whether that file really exists?

**Comment by FTD2018** [comment]
I have added the "print(i)" line, and the output is:
![图片](https://user-images.githubusercontent.com/34161876/121793825-5406d900-cc35-11eb-8910-c048a657cb1d.png)

**Comment by FTD2018** [comment]
Hi, Alexander:
I think the problem is the "path" problem.
the command "collect_results.py -n human.sorted.merged.enhancer -r ./ -a /data01/xuxiaopeng/target_analysis/MARVEL/human.enhancer.bed -o ./"

In your collect_results.py line 27 "name_prefix = args.result_path + args.region_name", the name_prefix = "./human.sorted.merged.enhancer", so 

for i in sorted(glob(name_prefix + "*_profiles.npz")):
    profiles.append(load_npz(i))

the profiles is empty.

The *_profiles.npz is in the path: **/data01/xuxiaopeng/target_analysis/MARVEL/results/test/*_chunks/***_profiles.npz

Looking forward to your reply

thanks

**Comment by fuxialexander** [comment]
Sorry that I forgot to check github notification recently. 
Theoretically when starting a nextflow process the files should be linked to the work dir, so the path "./" should be fine. However this path */data01/xuxiaopeng/target_analysis/MARVEL/results/test/_chunks/* looks a bit different from what I'd expect. It should be either "enhancer_chunk" or "promoter_chunk".

Can you add 'scan_input.view()' to line 625 and report the printed info?

**Comment by FTD2018** [comment]
Thanks for your responses.

Actually, in order to avoid the path or variable name problems, I have replaced the contents in the test_input folder with my own data but keep the same name. So the MARVEL worked.

But I have some questions about the results. My data is the target sequencing of several GWAS loci. 

1: In the summary folder, the csv file gives the motifs, but how can I simply know which motif is affected by which variant.
2: How can I provide other motifs (such as JASPAR) to the MARVEL instead of HOCOMOCO?
3: For the threshold, can I set a loose FDR value to be considered as significant because of the much less enhancers in the target regions than the whole genome. In other words, is the fdr value correlated with both p-val and enhancer numbers or just p-val, because the p-val: 8.96E-6, FDR:0.125 in my result, and p-val: 9.77E-6, FDR: 0.059 in your published paper. 
4: It is a little weird about the pdf file, looks like this (somehow, I can't upload the picture.......):

Do you have any suggestions?
Thanks

**Comment by fuxialexander** [comment]
> 1: In the summary folder, the csv file gives the motifs, but how can I simply know which motif is affected by which variant.
> 

I did not include that function. What I did before is to rescan the  sequence with FIMO or MOODS and overlap the motif site with the variants.

> 2: How can I provide other motifs (such as JASPAR) to the MARVEL instead of HOCOMOCO?

You can search for HOCOMOCO in the  bin/get_hocomoco_motif.sh file and replace it with the desired url
> 
> 3: For the threshold, can I set a loose FDR value to be considered as significant because of the much less enhancers in the target regions than the whole genome. In other words, is the fdr value correlated with both p-val and enhancer numbers or just p-val, because the p-val: 8.96E-6, FDR:0.125 in my result, and p-val: 9.77E-6, FDR: 0.059 in your published paper. 

I think FDR is related to both p-value ranking and total test number. Using a looser threshold may involves further argument with journal reviewers, you might consider try other multiple hypothesis testing approaches like BH, BY, etc. In the worst case you can focus on the top ones and do some experiment validation.

> 
> 4: It is a little weird about the pdf file, looks like this (somehow, I can't upload the picture.......):

Maybe you can send it to my email? fuxialexander [at] gmail [dot] com
> 
> 
> 
> Do you have any suggestions?
> 
> Thanks
